name: Update Mod List

on:
  push:
    branches:
      - main  # This triggers the action whenever there's a push to the 'main' branch

jobs:
  update-mod-list:
    runs-on: ubuntu-latest  # Use a Ubuntu-based environment for running the action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your code so the action can access it

      - name: Append new mod to mods.txt
        run: |
          # Extract the mod name and GitHub link from the commit message or another source
          MOD_NAME="New Mod"
          GITHUB_LINK="https://github.com/user/repo"  # Replace with actual mod data

          # Check if mods.txt exists, if not, create it
          if [ ! -f mods.txt ]; then
            echo "No mods found. Creating mods.txt."
            echo "$MOD_NAME | $GITHUB_LINK" > mods.txt
          else
            echo "$MOD_NAME | $GITHUB_LINK" >> mods.txt  # Append the new mod to the list
          fi

          # Commit and push changes to the repository
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add mods.txt
          git commit -m 'Update mod list with new mod'
          git push
